In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics import pairwise_distances
from src.config import cols

In [3]:
df = pd.read_excel("data/data_for_regression_GB.xlsx")

In [4]:
df.columns[0:30]

Index(['Unnamed: 0', 'deal_value', 'premium_1d', 'premium_1w', 'premium_4w',
       'premium_1m', 'acquiror_car_63', 'log_deal_value', 'deal_to_ebit',
       'deal_to_ebitda', 'deal_to_net_assets', 'target_market_value',
       'acquiror_market_value', 'relative_market_value', 'target_roe',
       'target_book_value_per_share', 'target_price_to_book_value',
       'target_long_term_debt_to_cap', 'target_full_name',
       'target_total_assets', 'target_debt_ratio',
       'acquiror_book_value_per_share', 'acquiror_price_to_book_value',
       'acquiror_roe', 'acquiror_debt_ratio', 'relative_total_assets',
       'cross_nation', 'cross_industry', 'number_of_bidders',
       'number_esg_raters'],
      dtype='str')

In [7]:
df = df.fillna(0)

In [8]:
df = df[cols]

In [36]:
y = df["has_green_bond"]

X = df[["relative_total_assets", "deal_year", "cross_nation", "cross_industry", "IG"]]
X = sm.add_constant(X)

logit = sm.Logit(y, X).fit()

df["pscore"] = logit.predict(X)

Optimization terminated successfully.
         Current function value: 0.177180
         Iterations 10

C:\Users\joel.sarkisyan\AppData\Local\Temp\ipykernel_25808\1045590133.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["pscore"] = logit.predict(X)

In [37]:
treated = df[df["has_green_bond"] == 1]
controls = df[df["has_green_bond"] == 0]

In [38]:
nn = NearestNeighbors(n_neighbors=3)
nn.fit(controls[["pscore"]])

distances, indices = nn.kneighbors(treated[["pscore"]])


matched_controls = controls.iloc[indices.flatten()]

In [39]:
matched_sample = pd.concat([treated, matched_controls])

In [40]:
matched_sample.to_excel("data/matched_sample.xlsx", index=False)

In [41]:
matched_sample[matched_sample["deal_year"] == 2023]

,Unnamed: 0,deal_value,premium_1d,premium_1w,premium_4w,premium_1m,acquiror_car_63,log_deal_value,deal_to_ebit,deal_to_ebitda,...,ESG Bond,Issue Price,Yield to Maturity,Details,Lead Underwriter,Use of Proceeds,Minimum Denomination,has_green_bond,relative_GB_amount,pscore
517,517,3582.821405,102.84,113.35,78.81,78.81,0.000000,8.183906,2.256578,1.096122,...,Yes,100.00,--,0,ZHESHANG SECURITIES CO LTD,Eligible Green Projects,100000.0,1,2713.189471,0.066861
526,526,86.543409,-9.33,-8.43,-5.06,-5.06,0.000000,4.460646,1.431141,0.342786,...,Yes,100.00,--,0,HAITONG SECURITIES CO LTD,Environmental Protection Projects,100.0,1,8190.453554,0.068113
531,531,346.435875,28.37,29.31,31.29,31.29,0.000000,5.847698,11.621949,4.524263,...,Yes,100.00,--,0,DAIWA SECURITIES CO LTD,Environmentally Sustainable Products,100000000.0,1,24879.446651,0.068113
532,532,2819.671898,0.00,-2.20,-8.73,-8.73,0.000000,7.944376,1.668320,0.978887,...,Yes,99.55,3.340628,Sr Note Freq Annual,ING BANK NV,Circular Economy Adapted/Eco-efficient Product...,100000.0,1,18054.038038,0.048723
514,514,116.136367,-7.98,-7.52,-3.15,-3.15,0.000000,4.754765,0.326421,0.173652,...,0,0.00,0,0,0,0,0.0,0,0.000000,0.042246
543,543,7.232046,-21.30,-10.73,40.58,40.58,0.000000,1.978522,0.516271,0.381400,...,0,0.00,0,0,0,0,0.0,0,0.000000,0.067259
522,522,372.183286,-6.96,-2.87,0.04,0.04,0.043846,5.919386,0.013637,0.006626,...,0,0.00,0,0,0,0,0.0,0,0.000000,0.066356
542,542,27.309856,58.13,79.38,182.49,182.49,0.000000,3.307248,1.949557,1.440255,...,0,0.00,0,0,0,0,0.0,0,0.000000,0.067433
506,506,292.525962,73.61,79.65,72.78,72.78,0.000000,5.678553,11.337245,9.649943,...,0,0.00,0,0,0,0,0.0,0,0.000000,0.068113
458,458,15215.352990,-7.17,-0.65,4.57,4.57,0.000000,9.630060,19.385130,10.348900,...,0,0.00,0,0,0,0,0.0,0,0.000000,0.068113
477,477,1176.325000,131.79,135.00,106.19,106.19,0.000000,7.070150,17.828779,9.710058,...,0,0.00,0,0,0,0,0.0,0,0.000000,0.068113
506,506,292.525962,73.61,79.65,72.78,72.78,0.000000,5.678553,11.337245,9.649943,...,0,0.00,0,0,0,0,0.0,0,0.000000,0.068113
458,458,15215.352990,-7.17,-0.65,4.57,4.57,0.000000,9.630060,19.385130,10.348900,...,0,0.00,0,0,0,0,0.0,0,0.000000,0.068113
477,477,1176.325000,131.79,135.00,106.19,106.19,0.000000,7.070150,17.828779,9.710058,...,0,0.00,0,0,0,0,0.0,0,0.000000,0.068113

In [42]:
matched_sample[matched_sample["deal_year"] == 2023]

,Unnamed: 0,deal_value,premium_1d,premium_1w,premium_4w,premium_1m,acquiror_car_63,log_deal_value,deal_to_ebit,deal_to_ebitda,...,ESG Bond,Issue Price,Yield to Maturity,Details,Lead Underwriter,Use of Proceeds,Minimum Denomination,has_green_bond,relative_GB_amount,pscore
517,517,3582.821405,102.84,113.35,78.81,78.81,0.000000,8.183906,2.256578,1.096122,...,Yes,100.00,--,0,ZHESHANG SECURITIES CO LTD,Eligible Green Projects,100000.0,1,2713.189471,0.066861
526,526,86.543409,-9.33,-8.43,-5.06,-5.06,0.000000,4.460646,1.431141,0.342786,...,Yes,100.00,--,0,HAITONG SECURITIES CO LTD,Environmental Protection Projects,100.0,1,8190.453554,0.068113
531,531,346.435875,28.37,29.31,31.29,31.29,0.000000,5.847698,11.621949,4.524263,...,Yes,100.00,--,0,DAIWA SECURITIES CO LTD,Environmentally Sustainable Products,100000000.0,1,24879.446651,0.068113
532,532,2819.671898,0.00,-2.20,-8.73,-8.73,0.000000,7.944376,1.668320,0.978887,...,Yes,99.55,3.340628,Sr Note Freq Annual,ING BANK NV,Circular Economy Adapted/Eco-efficient Product...,100000.0,1,18054.038038,0.048723
514,514,116.136367,-7.98,-7.52,-3.15,-3.15,0.000000,4.754765,0.326421,0.173652,...,0,0.00,0,0,0,0,0.0,0,0.000000,0.042246
543,543,7.232046,-21.30,-10.73,40.58,40.58,0.000000,1.978522,0.516271,0.381400,...,0,0.00,0,0,0,0,0.0,0,0.000000,0.067259
522,522,372.183286,-6.96,-2.87,0.04,0.04,0.043846,5.919386,0.013637,0.006626,...,0,0.00,0,0,0,0,0.0,0,0.000000,0.066356
542,542,27.309856,58.13,79.38,182.49,182.49,0.000000,3.307248,1.949557,1.440255,...,0,0.00,0,0,0,0,0.0,0,0.000000,0.067433
506,506,292.525962,73.61,79.65,72.78,72.78,0.000000,5.678553,11.337245,9.649943,...,0,0.00,0,0,0,0,0.0,0,0.000000,0.068113
458,458,15215.352990,-7.17,-0.65,4.57,4.57,0.000000,9.630060,19.385130,10.348900,...,0,0.00,0,0,0,0,0.0,0,0.000000,0.068113
477,477,1176.325000,131.79,135.00,106.19,106.19,0.000000,7.070150,17.828779,9.710058,...,0,0.00,0,0,0,0,0.0,0,0.000000,0.068113
506,506,292.525962,73.61,79.65,72.78,72.78,0.000000,5.678553,11.337245,9.649943,...,0,0.00,0,0,0,0,0.0,0,0.000000,0.068113
458,458,15215.352990,-7.17,-0.65,4.57,4.57,0.000000,9.630060,19.385130,10.348900,...,0,0.00,0,0,0,0,0.0,0,0.000000,0.068113
477,477,1176.325000,131.79,135.00,106.19,106.19,0.000000,7.070150,17.828779,9.710058,...,0,0.00,0,0,0,0,0.0,0,0.000000,0.068113

In [9]:
treated = df[df["has_green_bond"] == 1]
controls = df[df["has_green_bond"] == 0]


vars = ["relative_total_assets", "deal_year", "cross_nation", "cross_industry", "IG", "deal_value"]


treated = treated.dropna(subset=vars)
controls = controls.dropna(subset=vars)


X = df[vars].dropna()
cov = np.cov(X.T)
inv_cov = np.linalg.inv(cov)


dist_matrix = pairwise_distances(
    treated[vars],
    controls[vars],
    metric="mahalanobis",
    VI=inv_cov
)

k = 3

matches = []

for i in range(len(treated)):
    idx = np.argsort(dist_matrix[i])[:k]
    matched_controls = controls.iloc[idx]
    matches.append(matched_controls)

matched_controls_df = pd.concat(matches)
matched_sample = pd.concat([treated, matched_controls_df])

In [10]:
matched_sample[matched_sample["deal_year"] == 2008]

,relative_total_assets,deal_year,cross_nation,cross_industry,IG,deal_value,target_GB_amount,relative_GB_amount,has_green_bond,target_full_name
26,0.000000,2008,0,1,0,249.373782,319621568.0,112537.262314,1,Elisa Oyj
23,0.000000,2008,0,1,0,217.374018,0.0,0.000000,0,Finmeccanica SpA
11,3.163657,2008,0,1,0,956.456785,0.0,0.000000,0,FKI PLC
16,0.000000,2008,0,1,0,2401.644049,0.0,0.000000,0,Enodis PLC